# Generated by Django 5.2.7 on 2025-10-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redirect',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='redirect',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='redirect',
            name='total_accesses',
        ),
        migrations.RemoveField(
            model_name='redirect',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='redirect',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='redirect',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
